#!/usr/bin/env python3
"""Script to create sample Office files for testing."""

from pathlib import Path

# Create input directory
input_dir = Path(__file__).parent / "input"
input_dir.mkdir(exist_ok=True)

print("Creating sample Office files...")

# Create DOCX sample
try:
    from docx import Document

    doc = Document()
    doc.add_heading("Sample Word Document", 0)
    doc.add_paragraph("This is a sample paragraph with some text.")
    doc.add_heading("Section 1", level=1)
    doc.add_paragraph("Content for section 1.")
    doc.add_heading("Section 2", level=2)
    doc.add_paragraph("Content for section 2 with more details.")

    # Add a table
    table = doc.add_table(rows=3, cols=3)
    table.style = "Table Grid"
    headers = table.rows[0].cells
    headers[0].text = "Name"
    headers[1].text = "Age"
    headers[2].text = "City"

    row1 = table.rows[1].cells
    row1[0].text = "Alice"
    row1[1].text = "30"
    row1[2].text = "New York"

    row2 = table.rows[2].cells
    row2[0].text = "Bob"
    row2[1].text = "25"
    row2[2].text = "San Francisco"

    doc.save(input_dir / "sample.docx")
    print("✓ Created sample.docx")
except ImportError:
    print("⚠ python-docx not installed, skipping DOCX sample")

# Create XLSX sample
try:
    from openpyxl import Workbook

    wb = Workbook()
    ws = wb.active
    ws.title = "Sales Data"

    # Add headers
    ws["A1"] = "Product"
    ws["B1"] = "Quantity"
    ws["C1"] = "Price"
    ws["D1"] = "Total"

    # Add data
    data = [
        ("Widget A", 10, 19.99, 199.90),
        ("Widget B", 5, 29.99, 149.95),
        ("Widget C", 15, 9.99, 149.85),
    ]

    for row_idx, row_data in enumerate(data, start=2):
        for col_idx, value in enumerate(row_data, start=1):
            ws.cell(row=row_idx, column=col_idx, value=value)

    # Add a second sheet
    ws2 = wb.create_sheet("Summary")
    ws2["A1"] = "Total Products"
    ws2["B1"] = 3
    ws2["A2"] = "Total Revenue"
    ws2["B2"] = 499.70

    wb.save(input_dir / "sample.xlsx")
    print("✓ Created sample.xlsx")
except ImportError:
    print("⚠ openpyxl not installed, skipping XLSX sample")

# Create PPTX sample
try:
    from pptx import Presentation
    from pptx.util import Inches, Pt

    prs = Presentation()

    # Title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "Sample Presentation"
    subtitle.text = "Generated by office2md"

    # Content slide 1
    bullet_slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]

    title_shape.text = "Key Features"
    tf = body_shape.text_frame
    tf.text = "Easy to use"

    p = tf.add_paragraph()
    p.text = "High quality conversion"
    p.level = 0

    p = tf.add_paragraph()
    p.text = "Supports multiple formats"
    p.level = 0

    # Content slide 2
    slide = prs.slides.add_slide(bullet_slide_layout)
    title_shape = slide.shapes.title
    body_shape = slide.placeholders[1]

    title_shape.text = "Supported Formats"
    tf = body_shape.text_frame
    tf.text = "Microsoft Word (.docx)"

    p = tf.add_paragraph()
    p.text = "Microsoft Excel (.xlsx, .xls)"
    p.level = 0

    p = tf.add_paragraph()
    p.text = "Microsoft PowerPoint (.pptx, .ppt)"
    p.level = 0

    prs.save(input_dir / "sample.pptx")
    print("✓ Created sample.pptx")
except ImportError:
    print("⚠ python-pptx not installed, skipping PPTX sample")

print("\nSample files created successfully!")
print(f"Location: {input_dir}")
